from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path(
        'get_balance_sheet/<str:ticker>/',
        views.get_balance_sheet,
        name="get-balance-sheet"
    ),
    path(
        'get_cash_flow/<str:ticker>/',
        views.get_cash_flow,
        name="get-cash-flow"
    ),
    path(
        'get_historical_data/<str:ticker>/',
        views.get_historical_data,
        name="get-historical-data"
    ),
    path(
        'get_sector_and_industry/<str:ticker>/',
        views.get_sector_and_industry,
        name="get-sector-and-industry"
    ),
    path(
        'get_calendar/<str:ticker>/',
        views.get_calendar,
        name="get-calendar"
    ),
    path(
        'get_news/<str:ticker>/',
        views.get_news,
        name="get-news"
    ),
    path(
        'get_profile/<str:ticker>/',
        views.get_profile,
        name="get-profile"
    ),
    path(
        'get_analysis_data/<str:ticker>/',
        views.get_analysis_data,
        name="get-analysis-data"
    ),
    path(
        'get_stock_stats/<str:ticker>/<int:quarters>/',
        views.get_stock_statistics,
        name="get-stock-statistics"
    ),
    path(
        'get_income_statement/<str:ticker>/',
        views.get_income_statement,
        name="get-income-statement"
    ),
    path(
        'get_multiple_historical_data/',
        views.get_multiple_historical_data,
        name="get-multiple-historical-data"
    ),
    path(
        'get_yesterday_and_today_closing_data/',
        views.get_yesterday_and_today_closing_data,
        name="get-yesterday-and-today-closing-data"
    ),
    path(
        'get_valuation_measures/<str:ticker>/',
        views.get_valuation_measures,
        name="get-valuation-measures"
    ),
    path(
        'get_trending_tickers/',
        views.get_trending_tickers,
        name="get-trending-tickers"
    ),
    path(
        'get_key_statistics/<str:ticker>/',
        views.get_key_statistics,
        name="get-key-statistics"
    ),
    path(
        'get_world_indices',
        views.get_world_indices,
        name="get-world-indices"
    ),
    path(
        'search',
        views.search,
        name="search"    
    ),
    path(
        'get_currency_data',
        views.get_currency_data,
        name="get-currency-data"
    ),
    path(
        'get_list_of_currencies',
        views.get_list_of_currencies,
        name="get-list-of-currencies"
    ),
    path(
        'get_exchanges',
        views.get_exchanges,
        name="get-exchanges"
    ),
    path(
        'get_market_summary/<str:country>',
        views.get_market_summary,
        name="get-market-summary"
    ),
    path(
        'get_market_summary/',
        views.get_market_summary,
        name="get-market-summary-default"
    ),
    path(
        'get_list_of_trending_stocks_countrywise/<str:country>',
        views.get_list_of_trending_stocks_countrywise,
        name="get-list-of-trending-stocks-countrywise"
    ),
    path(
        'get_most_active',
        views.get_most_active,
        name="get-most-active"
    ),
    path(
        'get_top_gainers',
        views.get_top_gainers,
        name="get-top-gainers"
    ),
    path(
        'get_top_losers',
        views.get_top_losers,
        name="get-top-losers"
    ),
    path(
        'get_52week_gainers',
        views.get_52week_gainers,
        name="get-52week-gainers"
    ),
    path(
        'get_52week_losers',
        views.get_52week_losers,
        name="get-52week-losers"
    ),
    path(
        'get_asset_profile/<str:symbols>/',
        views.get_asset_profile,
        name="get-asset-profile"
    ),
    path(
        'get_calendar_events/<str:ticker>/',
        views.get_calendar_events,
        name="get-calendar-events"
    ),
    path(
        'get_company_officers/<str:ticker>/',
        views.get_company_officers,
        name="get-company-officers"
    ),
    path(
        'get_earning_history/<str:ticker>/',
        views.get_earning_history,
        name="get-earning-history"
    ),
    path(
        'get_earnings/<str:ticker>/',
        views.get_earnings,
        name="get-earnings"
    ),
    path(
        'get_earnings_trend/<str:ticker>/',
        views.get_earnings_trend,
        name="get-earnings-trend"
    ),
    path(
        'get_esg_scores/<str:ticker>/',
        views.get_esg_scores,
        name="get-esg-scores"
    ),
    path(
        'get_financial_data/<str:ticker>/',
        views.get_financial_data,
        name="get-financial-data"
    ),
    path(
        'get_fund_bond_holdings/<str:ticker>/',
        views.get_fund_bond_holdings,
        name="get-fund-bond-holdings"
    ),
    path(
        'get_fund_bond_ratings',
        views.get_fund_bond_ratings,
        name="get-fund-bond-ratings"
    ),
    path(
        'get_fund_equity_holdings/<str:ticker>/',
        views.get_fund_equity_holdings,
        name="get-fund-equity-holdings"
    ),
    path(
        'get_fund_holding_info/<str:ticker>/',
        views.get_fund_holding_info,
        name="get-fund-holding-info"
    ),
    path(
        'get_fund_ownership/<str:ticker>/',
        views.get_fund_ownership,
        name="get-fund-holding-info"
    ),
    path(
        'get_fund_performance/<str:ticker>/',
        views.get_fund_performance,
        name="get-fund-performance"
    ),
    path(
        'get_fund_profile/<str:ticker>/',
        views.get_fund_profile,
        name="get-fund-profile"
    ),
    path(
        'get_fund_sector_weightings/<str:ticker>/',
        views.get_fund_sector_weightings,
        name="get-fund-sector-weightings"
    ),
    path(
        'get_fund_top_holdings/<str:ticker>/',
        views.get_fund_top_holdings,
        name="get-fund-top-holdings"
    ),
    path(
        'get_grading_history/<str:ticker>/',
        views.get_grading_history,
        name="get-grading-history"
    ),
    path(
        'get_index_trend/<str:ticker>/',
        views.get_index_trend,
        name="get-index-trend"
    ),
    path(
        'get_industry_trend/<str:ticker>/',
        views.get_industry_trend,
        name="get-industry-trend"
    ),
    path(
        'get_insider_holders/<str:ticker>/',
        views.get_insider_holders,
        name="get-insider-holders"
    ),
    path(
        'get_insider_transactions/<str:ticker>/',
        views.get_insider_transactions,
        name="get-insider-transactions"
    ),
    path(
        'get_institution_ownership/<str:ticker>/',
        views.get_institution_ownership,
        name="get-institution-ownership"
    ),
    path(
        'get_major_holders/<str:ticker>/',
        views.get_major_holders,
        name="get-major-holders"
    ),
    path(
        'get_page_views/<str:ticker>/',
        views.get_page_views,
        name="get-page-views"
    ),
    path(
        'get_price/<str:ticker>/',
        views.get_price,
        name="get-price"
    ),
    path(
        'get_quote_type/<str:ticker>/',
        views.get_quote_type,
        name="get-quote-type"
    ),
    path(
        'get_recommendation_trend/<str:ticker>/',
        views.get_recommendation_trend,
        name="get-recommendation-trend"
    ),
    path(
        'get_sec_filings/<str:ticker>/',
        views.get_sec_filings,
        name="get-sec-filings"
    ),
    path(
        'get_share_purchase_activity/<str:ticker>/',
        views.get_share_purchase_activity,
        name="get-share-purchase-activity"
    ),
    path(
        'get_summary_detail/<str:ticker>/',
        views.get_summary_detail,
        name="get-summary-detail"
    ),
    path(
        'get_summary_profile/<str:ticker>/',
        views.get_summary_profile,
        name="get-summary-profile"
    ),
    path(
        'get_available_screeners',
        views.get_available_screeners,
        name="get-available-screeners"
    ),
    path(
        'get_screeners/',
        views.get_screeners,
        name="get-screeners"
    ),
    path(
        'get_corporate_events/<str:ticker>/',
        views.get_corporate_events,
        name="get-corporate-events"
    ),
    path(
        'get_recommendations/<str:tickers>/',
        views.get_recommendations,
        name="get-recommendations"
    ),
    path(
        'get_technical_insights/<str:tickers>/',
        views.get_technical_insights,
        name="get-technical-insights"
    ),
     path('sector/<str:sector_key>/overview/', 
        views.get_sector_overview, 
        name='sector-overview'
    ),
    path('sector/<str:sector_key>/industries/', 
        views.get_sector_industries, 
        name='sector-industries'
    ),
    path('sector/<str:sector_key>/top_companies/', 
        views.get_sector_top_companies, 
        name='sector-companies-top-companies'
    ),
    path('sector/<str:sector_key>/top_etfs/', 
        views.get_sector_etfs, 
        name='sector-etfs'
    ),
    path('sector/<str:sector_key>/top_mutual_funds/', 
        views.get_sector_mutual_funds, 
        name='sector-mutual-funds'
    ),
    path('sector/<str:sector_key>/research_reports/', 
        views.get_sector_research, 
        name='sector-research-reports'
    ),
]
