from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path(
        'get_balance_sheet/<str:ticker>/',
        views.get_balance_sheet,
        name="get-balance-sheet"
    ),
    path(
        'get_cash_flow/<str:ticker>/',
        views.get_cash_flow,
        name="get-cash-flow"
    ),
    path(
        'get_historical_data/<str:ticker>/',
        views.get_historical_data,
        name="get-historical-data"
    ),
    path(
        'get_sector_and_industry/<str:ticker>/',
        views.get_sector_and_industry,
        name="get-sector-and-industry"
    ),
    path(
        'get_calendar/<str:ticker>/',
        views.get_calendar,
        name="get-calendar"
    ),
    path(
        'get_news/<str:ticker>/',
        views.get_news,
        name="get-news"
    ),
    path(
        'get_profile/<str:ticker>/',
        views.get_profile,
        name="get-profile"
    ),
    path(
        'get_analysis_data/<str:ticker>/',
        views.get_analysis_data,
        name="get-analysis-data"
    ),
    path(
        'get_stock_stats/<str:ticker>/<int:quarters>/',
        views.get_stock_statistics,
        name="get-stock-statistics"
    ),
    path(
        'get_income_statement/<str:ticker>/',
        views.get_income_statement,
        name="get-income-statement"
    ),
    path(
        'get_multiple_historical_data/',
        views.get_multiple_historical_data,
        name="get-multiple-historical-data"
    ),
    path(
        'get_yesterday_and_today_closing_data/',
        views.get_yesterday_and_today_closing_data,
        name="get-yesterday-and-today-closing-data"
    ),
    path(
        'get_valuation_measures/<str:ticker>',
        views.get_valuation_measures,
        name="get-valuation-measures"
    ),
    path(
        'get_trending_tickers/',
        views.get_trending_tickers,
        name="get-trending-tickers"
    ),
    path(
        'get_key_statistics/<str:ticker>',
        views.get_key_statistics,
        name="get-key-statistics"
    ),
]
